name: Latest blog post
on:
  schedule:
    - cron: '0 0 1 * *' # Runs every month on the first day at 00:00 UTC
  workflow_dispatch:
jobs:
  update-readme-with-blog:
    name: Update this repo's README with latest blog posts
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: gautamkrishnar/blog-post-workflow@v1
        with:
          feed_list: "https://swissbuechi.github.io/feed.xml"